CREATE TABLE TB_DEPARTAMENTO (
	ID INT PRIMARY KEY NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	SIGLA VARCHAR(10)
);

CREATE TABLE USUARIO (
	TD INT PRIMARY KEY NOT NULL,
	TXT_NOME VARCHAR(50) NOT NULL,
	TXT_EMAIL VARCHAR(50) NOT NULL
);


CREATE TABLE ALUNO (
	ID INT PRIMARY KEY NOT NULL
);

CREATE TABLE TB_COORD_CURSO (
	ID INT PRIMARY KEY NOT NULL,
	TXT_NOME VARCHAR(50) NOT NULL,
	TXT_SIGLA VARCHAR(10),
	FK_DEPARTAMENTO INT REFERENCES TB_DEPARTAMENTO,
	FK_COORDENADOR INT REFERENCES USUARIO
);

CREATE TABLE TB_DISCIPLINAS (
	ID INT PRIMARY KEY NOT NULL,
	TXT_NOME VARCHAR(50) NOT NULL,
	TXT_CODIGO VARCHAR(10) NOT NULL,
	TXT_TURNO VARCHAR(10) NOT NULL,
	TXT_PERIODO VARCHAR(6) NOT NULL,
	FK_COORD_CURSO INT REFERENCES TB_COORD_CURSO,
	FK_PROFESSOR INT REFERENCES USUARIO
);

CREATE TABLE MONITORIA (
	ID INT PRIMARY KEY NOT NULL,
	BOLSA BOOLEAN NOT NULL,
	FK_ALUNO INT REFERENCES USUARIO,
	FK_DISCIPLINA INT REFERENCES USUARIO
);
