CREATE TABLE TB_DEPARTAMENTO (
	ID INT PRIMARY KEY NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	SIGLA VARCHAR(10)
);

CREATE TABLE TB_USUARIO (
	ID INT PRIMARY KEY NOT NULL,
	TXT_NOME VARCHAR(50) NOT NULL,
	TXT_EMAIL VARCHAR(50) NOT NULL
);


CREATE TABLE TB_ALUNO (
	ID_USUARIO INT PRIMARY KEY NOT NULL REFERENCES TB_USUARIO,
	TXT_MATRICULA VARCHAR(50) NOT NULL
);

CREATE TABLE TB_PROFESSOR (
	ID_USUARIO INT PRIMARY KEY NOT NULL REFERENCES TB_USUARIO,
	INT_SIAPE INT NOT NULL
);

CREATE TABLE TB_COORD_CURSO (
	ID INT PRIMARY KEY NOT NULL,
	TXT_NOME VARCHAR(50) NOT NULL,
	TXT_SIGLA VARCHAR(10),
	FK_DEPARTAMENTO INT REFERENCES TB_DEPARTAMENTO,
	FK_COORDENADOR INT REFERENCES TB_USUARIO
);

CREATE TABLE TB_DISCIPLINA (
	ID INT PRIMARY KEY NOT NULL,
	TXT_NOME VARCHAR(50) NOT NULL,
	TXT_CODIGO VARCHAR(10) NOT NULL,
	TXT_TURNO VARCHAR(10) NOT NULL,
	TXT_PERIODO VARCHAR(6) NOT NULL,
	FK_COORD_CURSO INT REFERENCES TB_COORD_CURSO,
	FK_PROFESSOR INT REFERENCES TB_USUARIO
);

CREATE TABLE TB_MONITORIA (
	ID INT PRIMARY KEY NOT NULL,
	BOOL_BOLSA BOOLEAN NOT NULL,
	FK_ALUNO INT REFERENCES TB_USUARIO,
	FK_DISCIPLINA INT REFERENCES TB_USUARIO
);
