CREATE OR REPLACE TABLE TB_DEPARTAMENTO (
	ID INT PRIMARY KEY NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	SIGLA VARCHAR(10)
);

CREATE OR REPLACE TABLE USUARIO (
	TD INT PRIMARY KEY NOT NULL,
	TXT_NOME NOT NULL,
	TXT_EMAIL NOT NULL
);


CREATE OR REPLACE TABLE ALUNO (
	ID INT PRIMARY KEY NOT NULL
);

CREATE OR REPLACE TABLE TB_COORD_CURSO (
	ID INT PRIMARY KEY NOT NULL,
	TXT_NOME VARCHAR(50) NOT NULL,
	TXT_SIGLA VARCHAR(10),
	FK_DEPARTAMENTO REFERENCES TB_DEPARTAMENTO (ID),
	FK_COORDENADOR REFERENCES USUARIO (ID)
);

CREATE OR REPLACE TABLE TB_DISCIPLINAS (
	ID INT PRIMARY KEY NOT NULL,
	TXT_NOME VARCHAR(50) NOT NULL,
	TXT_CODIGO VARCHAR(10) NOT NULL,
	TXT_TURNO VARCHAR(10) NOT NULL,
	TXT_PERIODO VARCHAR(6) NOT NULL
	FK_COORD_CURSO REFERENCES TB_COORD_CURSO (ID),
	FK_PROFESSOR REFERENCES USUARIO (ID)
);

CREATE OR REPLACE TABLE MONITORIA (
	ID INT PRIMARY KEY NOT NULL,
	BOLSA BOOLEAN NOT NULL
	FK_ALUNO REFERENCES USUARIO (ID),
	FK_DISCIPLINA REFERENCES USUARIO (ID)
);
);
